on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4
        
      - name: Configure GPG key
        run:
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          
      - name: Makepkg Build and Check sconf
        id: makepkg
        uses: edlanglois/pkgbuild-action@v1
        with:
          aurDeps: true
      - name: Print package files
        run: |
          echo "Successfully created the following package archives"
          echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
          echo "Package: ${{ steps.makepkg.outputs.pkgfile1 }}"
          echo "Package: ${{ steps.makepkg.outputs.pkgfile2 }}"
      - name: Upload sconf artifact
        uses: actions/upload-artifact@v4
        with:
          name: senior-apps
          path: |-
            ${{ steps.makepkg.outputs.pkgfile0 }}
            ${{ steps.makepkg.outputs.pkgfile1 }}
            ${{ steps.makepkg.outputs.pkgfile2 }}
      - name: Create arch repo
        run: |
          sudo apt-get update
          sudo apt-get install pacman-package-manager -y
          mkdir -p sapps/repo/x86_64
          pushd .
          cp **.pkg.tar.zst sapps/repo/x86_64
          cd sapps/repo/x86_64
          gpg --sign ${{ steps.makepkg.outputs.pkgfile0 }} --output ${{ steps.makepkg.outputs.pkgfile0 }}.sig
          gpg --sign ${{ steps.makepkg.outputs.pkgfile1 }} --output ${{ steps.makepkg.outputs.pkgfile1 }}.sig
          gpg --sign ${{ steps.makepkg.outputs.pkgfile2 }} --output ${{ steps.makepkg.outputs.pkgfile2 }}.sig
          repo-add --verify --sign --key A4B4A964B444DF8C71E717BEFF7208640955A234 sapps.db.tar.gz *.pkg.tar.zst
          popd
      - name: Publish repo artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: sapps/
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy repo to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
          
