on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'warning'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4
        
      - name: Configure GPG key
        run:
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          
      - name: Makepkg Build and Check sconf
        id: makepkg-sconf
        uses: samarthj/arch-pkgbuild-action@v2
        with:
          aur_username: ""
          aur_email: ""
          aur_ssh_private_key: ""
          setup_aur: false
          is_python_pkg: true
          dry_run: false
      - name: Print package files
        run: |
          echo "Successfully created the following package archives"
          echo "Package: ${{ steps.makepkg.outputs.pkg0 }}"
          echo "Package: ${{ steps.makepkg.outputs.pkg1 }}"
          echo "Package: ${{ steps.makepkg.outputs.pkg2 }}"
      - name: Upload sconf artifact
        uses: actions/upload-artifact@v4
        with:
          name: senior-apps
          path: |-
            ${{ steps.makepkg.outputs.pkg0 }}
            ${{ steps.makepkg.outputs.pkg1 }}
            ${{ steps.makepkg.outputs.pkg2 }}
