on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'warning'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4
        
      - name: Configure GPG key
        run:
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          
      - name: Makepkg Build and Check sconf
        id: makepkg
        uses: edlanglois/pkgbuild-action@v1
        with:
          aurDeps: true
      - name: Print package files
        run: |
          echo "Successfully created the following package archives"
          echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
          echo "Package: ${{ steps.makepkg.outputs.pkgfile1 }}"
          echo "Package: ${{ steps.makepkg.outputs.pkgfile2 }}"
      - name: Upload sconf artifact
        uses: actions/upload-artifact@v4
        with:
          name: senior-apps
          path: |-
            ${{ steps.makepkg.outputs.pkgfile0 }}
            ${{ steps.makepkg.outputs.pkgfile1 }}
            ${{ steps.makepkg.outputs.pkgfile2 }}
